export const  productCatagories = [
  "Électronique",
  "Téléphones & Accessoires",
  "Ordinateurs & Laptops",
  "Gaming",
  "Prêt à porter",
  "Électroménager",
  "Appareils de Cuisine",
  "Meubles",
  "Décoration",
  "Mode Homme",
  "Mode Femme",
  "Mode Enfants",
  "Chaussures",
  "Sacs & Accessoires",
  "Beauté & Soin Personnel",
  "Soins Capillaires",
  "Soins de la Peau",
  "Santé & Bien-être",
  "Sport & Fitness",
  "Outdoor & Camping",
  "Outils & Bricolage",
  "Automobile",
  "Équipement Moto",
  "Produits Bébé",
  "Jouets & Jeux",
  "Livres",
  "Papeterie & Fournitures de Bureau",
  "Animalerie",
  "Épicerie",
  "Nourriture & Boissons",
  "Bijoux",
  "Montres",
  "Maison Connectée",
  "TV & Audio",
  "Caméras & Photographie",
  "Art & Artisanat",
  "Instruments de Musique",
  "Produits de Nettoyage",
  "Jardin & Plantes",
  "Matériaux de Construction",
  "Fournitures Médicales",
  "Logiciels & Applications",
  "Services Digitaux",
  "Amélioration de la Maison"
]
